// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking_project.Data;

#nullable disable

namespace Parking_project.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260211143550_Fkey2")]
    partial class Fkey2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parking_project.Models.CilsimetParkimit", b =>
                {
                    b.Property<int>("CilsimetiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CilsimetiId"));

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NjesiteId")
                        .HasColumnType("int");

                    b.Property<int>("SherbimiId")
                        .HasColumnType("int");

                    b.HasKey("CilsimetiId");

                    b.HasIndex("NjesiteId");

                    b.HasIndex("SherbimiId");

                    b.ToTable("CilsimetParkimit");
                });

            modelBuilder.Entity("Parking_project.Models.Detajet", b =>
                {
                    b.Property<int>("DetajetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetajetId"));

                    b.Property<int>("CilsimetiId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FromHour")
                        .HasColumnType("int");

                    b.Property<int?>("ToHour")
                        .HasColumnType("int");

                    b.HasKey("DetajetId");

                    b.HasIndex("CilsimetiId");

                    b.ToTable("Detajet");
                });

            modelBuilder.Entity("Parking_project.Models.Lokacioni", b =>
                {
                    b.Property<int>("LokacioniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacioniId"));

                    b.Property<int>("Kati")
                        .HasColumnType("int");

                    b.Property<int>("NjesiteId")
                        .HasColumnType("int");

                    b.HasKey("LokacioniId");

                    b.HasIndex("NjesiteId");

                    b.ToTable("Lokacioni");
                });

            modelBuilder.Entity("Parking_project.Models.NjesiOrg", b =>
                {
                    b.Property<int>("NjesiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NjesiteId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BiznesId")
                        .HasColumnType("int");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Kodi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NjesiteId");

                    b.HasIndex("BiznesId");

                    b.ToTable("NjesiOrg");
                });

            modelBuilder.Entity("Parking_project.Models.Organizata", b =>
                {
                    b.Property<int>("BiznesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BiznesId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DataRegjistrimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmriBiznesit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Komuna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumriBiznesit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumriFiskal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumriPunetoreve")
                        .HasColumnType("int");

                    b.Property<string>("NumriUnikIdentifikues")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefoni")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BiznesId");

                    b.ToTable("Organizata");
                });

            modelBuilder.Entity("Parking_project.Models.Sherbimi", b =>
                {
                    b.Property<int>("SherbimiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SherbimiId"));

                    b.Property<int>("BiznesId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrganizataBiznesId")
                        .HasColumnType("int");

                    b.HasKey("SherbimiId");

                    b.HasIndex("BiznesId");

                    b.HasIndex("OrganizataBiznesId");

                    b.ToTable("Sherbimi");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionDetaj", b =>
                {
                    b.Property<int>("TransaksionId")
                        .HasColumnType("int");

                    b.Property<int>("SherbimiId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransaksionId", "SherbimiId");

                    b.HasIndex("SherbimiId");

                    b.ToTable("TransaksionDetaj");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionParkimi", b =>
                {
                    b.Property<int>("TransaksioniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaksioniId"));

                    b.Property<int>("CilsimiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KohaDaljes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KohaHyrjes")
                        .HasColumnType("datetime2");

                    b.Property<int>("NjesiaId")
                        .HasColumnType("int");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VendiParkimitId")
                        .HasColumnType("int");

                    b.HasKey("TransaksioniId");

                    b.HasIndex("CilsimiId");

                    b.HasIndex("NjesiaId");

                    b.HasIndex("VendiParkimitId");

                    b.ToTable("TransaksionParkimi", (string)null);
                });

            modelBuilder.Entity("Parking_project.Models.Useri", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BiznesId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Passwordi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("BiznesId");

                    b.ToTable("Useri");
                });

            modelBuilder.Entity("Parking_project.Models.Vendi", b =>
                {
                    b.Property<int>("VendiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendiId"));

                    b.Property<int>("LokacioniId")
                        .HasColumnType("int");

                    b.Property<string>("VendiEmri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendiId");

                    b.HasIndex("LokacioniId");

                    b.ToTable("Vendi");
                });

            modelBuilder.Entity("Parking_project.Models.CilsimetParkimit", b =>
                {
                    b.HasOne("Parking_project.Models.NjesiOrg", "NjesiOrg")
                        .WithMany()
                        .HasForeignKey("NjesiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.Sherbimi", "Sherbimi")
                        .WithMany()
                        .HasForeignKey("SherbimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NjesiOrg");

                    b.Navigation("Sherbimi");
                });

            modelBuilder.Entity("Parking_project.Models.Detajet", b =>
                {
                    b.HasOne("Parking_project.Models.CilsimetParkimit", "CilsimetParkimit")
                        .WithMany()
                        .HasForeignKey("CilsimetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CilsimetParkimit");
                });

            modelBuilder.Entity("Parking_project.Models.Lokacioni", b =>
                {
                    b.HasOne("Parking_project.Models.NjesiOrg", "NjesiOrg")
                        .WithMany()
                        .HasForeignKey("NjesiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NjesiOrg");
                });

            modelBuilder.Entity("Parking_project.Models.NjesiOrg", b =>
                {
                    b.HasOne("Parking_project.Models.Organizata", "Organizata")
                        .WithMany("NjesiOrg")
                        .HasForeignKey("BiznesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizata");
                });

            modelBuilder.Entity("Parking_project.Models.Sherbimi", b =>
                {
                    b.HasOne("Parking_project.Models.Organizata", "Organizata")
                        .WithMany()
                        .HasForeignKey("BiznesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.Organizata", null)
                        .WithMany("Sherbimi")
                        .HasForeignKey("OrganizataBiznesId");

                    b.Navigation("Organizata");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionDetaj", b =>
                {
                    b.HasOne("Parking_project.Models.Sherbimi", "Sherbimi")
                        .WithMany()
                        .HasForeignKey("SherbimiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.TransaksionParkimi", "TransaksionParkimi")
                        .WithMany()
                        .HasForeignKey("TransaksionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sherbimi");

                    b.Navigation("TransaksionParkimi");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionParkimi", b =>
                {
                    b.HasOne("Parking_project.Models.CilsimetParkimit", "Cilsimet")
                        .WithMany()
                        .HasForeignKey("CilsimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.NjesiOrg", "Njesia")
                        .WithMany()
                        .HasForeignKey("NjesiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.Vendi", "Vendi")
                        .WithMany()
                        .HasForeignKey("VendiParkimitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cilsimet");

                    b.Navigation("Njesia");

                    b.Navigation("Vendi");
                });

            modelBuilder.Entity("Parking_project.Models.Useri", b =>
                {
                    b.HasOne("Parking_project.Models.Organizata", "Organizata")
                        .WithMany()
                        .HasForeignKey("BiznesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizata");
                });

            modelBuilder.Entity("Parking_project.Models.Vendi", b =>
                {
                    b.HasOne("Parking_project.Models.Lokacioni", "Lokacioni")
                        .WithMany()
                        .HasForeignKey("LokacioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokacioni");
                });

            modelBuilder.Entity("Parking_project.Models.Organizata", b =>
                {
                    b.Navigation("NjesiOrg");

                    b.Navigation("Sherbimi");
                });
#pragma warning restore 612, 618
        }
    }
}
