// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parking_project.Data;

#nullable disable

namespace Parking_project.Migrations.PostgreSql
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20260911092223_InitialCreatePostgreSQL")]
    partial class InitialCreatePostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parking_project.Models.CilsimetParkimit", b =>
                {
                    b.Property<int>("CilsimetiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CilsimetiId"));

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NjesiteId")
                        .HasColumnType("integer");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.Property<int>("SherbimiId")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.HasKey("CilsimetiId");

                    b.HasIndex("NjesiteId");

                    b.HasIndex("SherbimiId");

                    b.ToTable("CilsimetParkimit");
                });

            modelBuilder.Entity("Parking_project.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ExpYear")
                        .HasColumnType("integer");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("Parking_project.Models.Detajet", b =>
                {
                    b.Property<int>("DetajetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetajetId"));

                    b.Property<int>("CilsimetiId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FromHour")
                        .HasColumnType("integer");

                    b.Property<int?>("ToHour")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.HasKey("DetajetId");

                    b.HasIndex("CilsimetiId");

                    b.ToTable("Detajet");
                });

            modelBuilder.Entity("Parking_project.Models.NjesiOrg", b =>
                {
                    b.Property<int>("NjesiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NjesiteId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("BiznesId")
                        .HasColumnType("integer");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Kodi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VendeTeLira")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.HasKey("NjesiteId");

                    b.HasIndex("BiznesId");

                    b.ToTable("NjesiOrg");
                });

            modelBuilder.Entity("Parking_project.Models.Organizata", b =>
                {
                    b.Property<int>("BiznesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BiznesId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AllowCustomers")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataRegjistrimit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmriBiznesit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Komuna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumriBiznesit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumriFiskal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumriPunetoreve")
                        .HasColumnType("integer");

                    b.Property<string>("NumriUnikIdentifikues")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("QRScanner")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefoni")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("BiznesId");

                    b.ToTable("Organizata");
                });

            modelBuilder.Entity("Parking_project.Models.Sherbimi", b =>
                {
                    b.Property<int>("SherbimiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SherbimiId"));

                    b.Property<int>("BiznesId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.HasKey("SherbimiId");

                    b.HasIndex("BiznesId");

                    b.ToTable("Sherbimi");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionDetaj", b =>
                {
                    b.Property<int>("TransaksionId")
                        .HasColumnType("integer");

                    b.Property<int>("SherbimiId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransaksionId", "SherbimiId");

                    b.HasIndex("SherbimiId");

                    b.ToTable("TransaksionDetaj");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionParkimi", b =>
                {
                    b.Property<int>("TransaksioniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransaksioniId"));

                    b.Property<int>("CilsimiId")
                        .HasColumnType("integer");

                    b.Property<string>("Identifikues")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("KohaDaljes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("KohaHyrjes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NjesiaId")
                        .HasColumnType("integer");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TransaksioniId");

                    b.HasIndex("CilsimiId");

                    b.HasIndex("NjesiaId");

                    b.HasIndex("UserId");

                    b.ToTable("TransaksionParkimi");
                });

            modelBuilder.Entity("Parking_project.Models.UserOrg", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("BiznesId")
                        .HasColumnType("integer");

                    b.Property<int?>("NjesiaId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BiznesId");

                    b.HasIndex("BiznesId");

                    b.HasIndex("NjesiaId");

                    b.ToTable("UserOrg");
                });

            modelBuilder.Entity("Parking_project.Models.Useri", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Passwordi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("Useri");
                });

            modelBuilder.Entity("Parking_project.Models.CilsimetParkimit", b =>
                {
                    b.HasOne("Parking_project.Models.NjesiOrg", "NjesiOrg")
                        .WithMany()
                        .HasForeignKey("NjesiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.Sherbimi", "Sherbimi")
                        .WithMany()
                        .HasForeignKey("SherbimiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NjesiOrg");

                    b.Navigation("Sherbimi");
                });

            modelBuilder.Entity("Parking_project.Models.Detajet", b =>
                {
                    b.HasOne("Parking_project.Models.CilsimetParkimit", "CilsimetParkimit")
                        .WithMany()
                        .HasForeignKey("CilsimetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CilsimetParkimit");
                });

            modelBuilder.Entity("Parking_project.Models.NjesiOrg", b =>
                {
                    b.HasOne("Parking_project.Models.Organizata", "Organizata")
                        .WithMany()
                        .HasForeignKey("BiznesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizata");
                });

            modelBuilder.Entity("Parking_project.Models.Sherbimi", b =>
                {
                    b.HasOne("Parking_project.Models.Organizata", "Organizata")
                        .WithMany()
                        .HasForeignKey("BiznesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizata");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionDetaj", b =>
                {
                    b.HasOne("Parking_project.Models.Sherbimi", "Sherbimi")
                        .WithMany()
                        .HasForeignKey("SherbimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.TransaksionParkimi", "TransaksionParkimi")
                        .WithMany()
                        .HasForeignKey("TransaksionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sherbimi");

                    b.Navigation("TransaksionParkimi");
                });

            modelBuilder.Entity("Parking_project.Models.TransaksionParkimi", b =>
                {
                    b.HasOne("Parking_project.Models.CilsimetParkimit", "Cilsimet")
                        .WithMany()
                        .HasForeignKey("CilsimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.NjesiOrg", "Njesia")
                        .WithMany()
                        .HasForeignKey("NjesiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.Useri", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cilsimet");

                    b.Navigation("Njesia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parking_project.Models.UserOrg", b =>
                {
                    b.HasOne("Parking_project.Models.Organizata", "Organizata")
                        .WithMany()
                        .HasForeignKey("BiznesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_project.Models.NjesiOrg", "Njesi")
                        .WithMany()
                        .HasForeignKey("NjesiaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Parking_project.Models.Useri", "User")
                        .WithMany("UserOrgs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Njesi");

                    b.Navigation("Organizata");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parking_project.Models.Useri", b =>
                {
                    b.Navigation("UserOrgs");
                });
#pragma warning restore 612, 618
        }
    }
}
